In [170]:
import numpy as np

In [ ]:
#array creation

In [3]:
#1-dimensional array of integers from 1 to 10.
array1 = np.array([value for value in range(1,11)])

In [5]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
#2-dimensional array with random float values of shape (3, 4).
array2 = np.random.rand(3,4)

In [25]:
array2

array([[0.45825473, 0.77736405, 0.50458939, 0.88353126],
       [0.56985124, 0.25175567, 0.26151885, 0.54007338],
       [0.91854647, 0.16949342, 0.0731481 , 0.89352854]])

In [33]:
#3-dimensional array of zeros with shape (2, 3, 4).
array3 = np.zeros((2,3,4))

In [35]:
array3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [37]:
#array operations

In [39]:
#Given two 1-dimensional arrays, perform element-wise addition, subtraction, multiplication, and division.
x = np.array([1,2,3,4])
y = np.array([6,7,8,9])

In [53]:
#operations
result_add = x+y
result_sub = x-y
result_mul = x*y
result_div = y/x

In [55]:
result_add

array([ 7,  9, 11, 13])

In [57]:
result_sub

array([-5, -5, -5, -5])

In [59]:
result_mul

array([ 6, 14, 24, 36])

In [61]:
result_div

array([6.        , 3.5       , 2.66666667, 2.25      ])

In [64]:
#Calculate the mean, median, and standard deviation of a given 1-dimensional array.

In [162]:
result_mean = np.mean(x)
result_median = np.median(x)
result_stddev = np.std(x)

In [164]:
result_mean

2.5

In [166]:
result_median

2.5

In [168]:
result_stddev

1.118033988749895

In [158]:
#Reshape a 1-dimensional array into a 2-dimensional array of shape (3,4).
a = np.array([value for value in range(1,13)])
reshaped_array = a.reshape(3,4)

In [160]:
reshaped_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [172]:
#Array Indexing and Slicing

In [182]:
#Extract the first row and last column of a 2-dimensional array.

In [184]:
#first row of 2d array
array2[0,:]

array([0.45825473, 0.77736405, 0.50458939, 0.88353126])

In [188]:
#last row of 2d array
array2[:,-1]

array([0.88353126, 0.54007338, 0.89352854])

In [190]:
#Reverse the order of elements in a 1-dimensional array.

In [214]:
rev = np.flip(array1)

In [216]:
rev

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [218]:
#Select elements from a 2-dimensional array that satisfy a specific condition (e.g., values greater than a certain threshold).

In [220]:
arrayx = np.array([[1,2,3,4],[2,3,56,13],[41,23,65,12]])

In [224]:
#even elements
res = arrayx[arrayx%2==0]
res

array([ 2,  4,  2, 56, 12])

In [228]:
#value greater than 10
res1 = arrayx[arrayx>10]
res1

array([56, 13, 41, 23, 65, 12])

In [230]:
#Array Broadcasting

In [234]:
#Add a scalar value to each element of a 2-dimensional arrayr
res2 = arrayx+2
res2

array([[ 3,  4,  5,  6],
       [ 4,  5, 58, 15],
       [43, 25, 67, 14]])

In [236]:
#Multiply a 1-dimensional array with a 2-dimensional array, leveraging NumPy's broadcasting rules.
arrayf = np.array([[1,2,3],[4,5,6]])
arrayg = np.array([2,2,2])
resfg = arrayf*arrayg
resfg

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [238]:
#Linear Algebra

In [240]:
#Calculate the dot product of two 1-dimensional arrays.
arrayv = np.array([1,2,3])
arrayh = np.array([4,5,6])
resDot =  np.dot(arrayv,arrayh)
resDot

32

In [242]:
#Compute the matrix multiplication of two 2-dimensional arrays.
e = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,4],[1,3],[2,7]])
resMul = np.matmul(e,y)
resMul

array([[10, 31],
       [25, 73]])

In [246]:
#Find the inverse and determinant of a square matrix
sq = np.array([[1,2,3],[4,5,6],[7,8,9]])
resInv = np.linalg.inv(sq)
resInv

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [250]:
resDet = np.linalg.det(sq)
resDet

-9.51619735392994e-16